### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by jorbbey**
I refactored the search functionality and connected it to a general api fetch file
Refactored Landing page data fetch (connected it to a general api fetch)
Refactored Location function—yet to connect it to the landing page data display
added search route
removed redundant data from the footer database ( to ensure unique key prop in the footer component)

### CODE REVIEW

**Comment by jorbbey** [comment]
I've worked on the search function, and now it's fine

i'm trying to replicate what eventbrite have on their location function; it works like a search function, but for location, when a location is input (either city or country), the result influences the landing page data, causing the landing page to display the result from the location search on each of the display categories [popular, latest, category, etc...] - i'm still on this; i'll resume tomorrow

you just make sure our responsiveness is on point, coz the tab responsiveness is really bad and try not to use fonts, widths and heights of fixed sizes

**Comment by Benaks** [comment]
okk welldone broo
on it!

**Comment by Benaks** [comment]
The search functionality isn't quite working.
It's not displaying any data
Is it working on your end?

**Comment by jorbbey** [comment]
Yes, I removed the useEffect hook, so until you press enter or click on the arrow-right button, it will not display.

**Comment by Benaks** [comment]
Ok, thanks.

**Pull request merged**
